apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: cluster-pipelines
spec:
  generators:
  - list:
      elements:
      - cluster: local
        url: https://kubernetes.default.svc
        values:
          name: ols-byok-rag-pipeline
          path: components/tekton/pipelines/ols-byok-rag/overlays/default
