apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  name: ols-byok-rag-pipelinerun
  namespace: ols-byok-rag
spec:
  pipelineRef:
    name: ols-byok-rag-pipeline
  taskRunTemplate:
    serviceAccountName: default
  timeouts:
    pipeline: 1h0m0s
  workspaces:
  - name: workspace
    volumeClaimTemplate:
      metadata:
        creationTimestamp: null
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        volumeMode: Filesystem