apiVersion: v1
kind: Secret
metadata:
    name: rh-accelerator-repo-token
    namespace: openshift-gitops
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    url: https://github.com/aszmuda/ai-accelerator.git
    password: ENC[AES256_GCM,data:1CHrIPaRg8KqADsCUJoQKenTx/oWEy0fJBjle/sSr7vnV/PBHifcvmOcsa5jZrsNBHIc6qGPHPc7cKZnrmlnhHUmIOOBTF7/7GowLGvbu1TzFWPp8BHJvae4IMmm,iv:+WJQJDBPHlvHv1772lymr/3a6Fr5dPkNDmMq4h1Yz4o=,tag:5N/2COwyIaRtSOUsFHfjKA==,type:str]
    username: ENC[AES256_GCM,data:seAjM3/LkU8=,iv:VD7jyD4JCFhOMDJIxQRe+xtjT+goNDVPT6xbhzg7hv4=,tag:On07OhoCDOylLz4LjirHCw==,type:str]
sops:
    age:
        - recipient: age14vjd7uegmqa8rdxcvc404094cnzqkzkrpyhhefyfspqpmd6fsu9s7ljkt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5YmQva3MyOWNRb29sQWhU
            Ylhta2l5KzExU0FLOVJjZTRhcE4rUDJWYjFvCmJ1b3BmelhTaGJld21jSnZOakRR
            K2t4c09uWTZ0dXRRaVRiWnBaRGhYYlEKLS0tIEVDUkNBcWFPN0JPS2hCVnFBUlpw
            YkMxSE5nZjNRL1MvWmU5T3FIZHhpOGsKQu5rYEEF1rj+8RkL8++o98+J606ZDjnJ
            CQyhS+fsIypvUyL5GDNes1ofrFr+mZWF0Qi1gSE+mM7WbAiWYMkLJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-04T00:58:11Z"
    mac: ENC[AES256_GCM,data:Uu1ZZCgoBn8WRx+YTKpTG1+LdyjwZa1ZO9EYEki1WV3SN3yUEFeJWhFyQtwOt54OkpOOrJWAELSBrV7DXnITfVJ3peyagy6tKSPB4DGxb18Us6oCLw1w5FMMDLBhQz7s8sfABlOLRy9mOuzq6eIpKcSxhhgeXWaJK0PY3GbTdGM=,iv:/AQ27WKxtdKxu4JlkT/HaIoPccfDvPtRx3UTtpI+X54=,tag:1FNLabHMvnFACoHmd9aURw==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|url)$
    version: 3.11.0