apiVersion: v1
kind: Secret
metadata:
    name: rh-accelerator-repo-token
    namespace: openshift-gitops
    labels:
        argocd.argoproj.io/secret-type: repository
stringData:
    url: https://github.com/aszmuda/ai-accelerator.git
    password: ENC[AES256_GCM,data:IVsiRSU+I/H8OCqPwYshQBPmdnhwrSsb+W8W9R2GJ+Wptk4gyo8PHbXjGIqzIsWfqFDXP/BgJh3ZN3YPGD6Kg2zxvqK4cHj/MjpVvjWVxhp+2QltTAHWQ5F6tdE5,iv:kYVQVc/R3m4ef56VIN+ppjEjlWnzG8xjsEbmb79n1aU=,tag:vGLIWTtFr9djVw7r6Fbkww==,type:str]
    username: ENC[AES256_GCM,data:CD5lOEPpWzM=,iv:DzemceXiHFUnOzUo9QjW5UE8yllFvSnhL/zGI9A3LrE=,tag:CGVoaiTiyeX47J/qX6NqIg==,type:str]
sops:
    age:
        - recipient: age14vjd7uegmqa8rdxcvc404094cnzqkzkrpyhhefyfspqpmd6fsu9s7ljkt5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhc1hoVCtWdmZyc3ZDMFE0
            M3NCRXBsMWNoVHNTcVNDM1QzM1JDYkVIQVhzClhKWVh3NXdJVlNsaTZZcUlJdy92
            dVd1TWM2c1plS1JYSHl4TDhyMTVmcG8KLS0tIDNpcVU3cE1URG12TWE2UDBNNFJq
            V2UxQ2NXWUhTTWlQdy9McExCSkVkNUkKFTDyWjX/e/5a94EokwZvPoB3OrIXsCED
            pi0RzI96OnI2gD4LmXyznpI43K3z/PPgRz3mOA/IgjxTpktuBzVh5Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-03T08:19:57Z"
    mac: ENC[AES256_GCM,data:pSxro4zpjr4ptqdcsM0vlKF4DRFX+MkdlmQP5W5wcbs9PbjQOihULU1ahqNxjY8g9csaL8CfzcgZL/FfVoOGyW4mi5DBy9kXEcR48e/lq04GZ2BsCYKn/fe54XYaJYi9qrnfHUyq3IaNECAzdqhb4ThUFakDGq5lNJi0xKxwBLA=,iv:epq8DdRrqg2mIFXegxM5Wxewa7+O2k5OMCIhOUXKc1s=,tag:X0t4ZlY/o+ah4zas70DX6Q==,type:str]
    unencrypted_regex: ^(apiVersion|metadata|kind|type|url)$
    version: 3.11.0
